import { access, mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";

import { createAgentRunner, type AgentRunInput } from "../src/agent.js";
import type { PlanBatch, PlanPart } from "../src/types.js";

describe("agent runners", () => {
  it("dry-run runner creates docs/generated/<part-id>.md", async () => {
    const input = await makeInput();
    const runner = createAgentRunner("dry-run");

    const result = await runner.run(input);
    const output = await readFile(path.join(input.worktreePath, "docs", "generated", "alpha.md"), "utf8");

    expect(result.ok).toBe(true);
    expect(output).toContain("Dry-run output for alpha");
    expect(output).toContain("Build alpha.");
  });

  it("dry-run runner writes done marker", async () => {
    const input = await makeInput();
    const runner = createAgentRunner("dry-run");

    await runner.run(input);

    await expect(access(input.doneMarkerPath)).resolves.toBeUndefined();
  });

  it("command runner executes fake-agent and creates output plus done marker", async () => {
    const input = await makeInput();
    const fakeAgentPath = path.resolve("examples", "fake-agent.mjs");
    const command = `${quote(process.execPath)} ${quote(fakeAgentPath)}`;
    const runner = createAgentRunner("command", { command });

    const result = await runner.run(input);
    const output = await readFile(path.join(input.worktreePath, "docs", "generated", "alpha.md"), "utf8");

    expect(result.ok).toBe(true);
    expect(output).toContain("Generated by fake-agent.");
    expect(output).toContain("Part: alpha");
    await expect(access(input.doneMarkerPath)).resolves.toBeUndefined();
  });

  it("command runner returns ok false for missing command", async () => {
    const input = await makeInput();
    const runner = createAgentRunner("command");

    const result = await runner.run(input);

    expect(result.ok).toBe(false);
    expect(result.error).toContain("requires a command");
  });

  it("command runner returns ok false for a failing command", async () => {
    const input = await makeInput();
    const command = `${quote(process.execPath)} -e "process.exit(7)"`;
    const runner = createAgentRunner("command", { command });

    const result = await runner.run(input);

    expect(result.ok).toBe(false);
    expect(result.exitCode).toBe(7);
  });
});

async function makeInput(): Promise<AgentRunInput> {
  const root = await mkdtemp(path.join(tmpdir(), "awo-agent-"));
  const worktreePath = path.join(root, "worktree");
  const promptPath = path.join(root, "prompts", "alpha.md");
  await mkdir(worktreePath, { recursive: true });
  await mkdir(path.dirname(promptPath), { recursive: true });
  await writeFile(promptPath, "Build alpha.", "utf8");

  const part: PlanPart = {
    id: "alpha",
    title: "Alpha",
    brief: "Build alpha.",
  };
  const batch: PlanBatch = {
    id: "batch-1",
    parts: [part],
  };

  return {
    repoPath: root,
    worktreePath,
    part,
    batch,
    fullPlanText: "version: 1",
    promptPath,
    logPath: path.join(root, "logs", "alpha.log"),
    doneMarkerPath: path.join(root, "done", "alpha.done"),
    timeoutMs: 10_000,
  };
}

function quote(value: string): string {
  return `"${value.replaceAll('"', '\\"')}"`;
}
