import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const partId = process.env.AWO_PART_ID;
const batchId = process.env.AWO_BATCH_ID;
const doneFile = process.env.AWO_DONE_FILE;
const worktree = process.env.AWO_WORKTREE ?? process.cwd();

if (!partId || !batchId || !doneFile) {
  console.error("Missing required AWO_PART_ID, AWO_BATCH_ID, or AWO_DONE_FILE environment variable.");
  process.exit(1);
}

const outputPath = path.join(worktree, "docs", "generated", `${partId}.md`);
await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  [
    `# Fake agent output for ${partId}`,
    "",
    "Generated by fake-agent.",
    "",
    `- Part: ${partId}`,
    `- Batch: ${batchId}`,
    "",
  ].join("\n"),
  "utf8",
);

await mkdir(path.dirname(doneFile), { recursive: true });
await writeFile(doneFile, `fake-agent completed ${batchId}/${partId}\n`, "utf8");
